# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'uberClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uberClone
	pod 'Firebase/Core'
	pod 'Firebase/Database', '~> 6.0'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'GeoFire', '~> 4.1.0'

end
